export const TASKS_LIST_ROUTE = '/tasks'
export const BOARDS_ROUTE = '/boards'
export const INFO_ROUTE = '/info'
export const SETTINGS_ROUTE = '/settings'
export const PROJECT_ROUTE = '/project'
export const PROJECT_DETAILS_ROUTE = '/project/:id'
export const AUTH_ROUTE = '/auth'
export const REGISTRATION_ROUTE = '/registration'